/** 专属于 Button 的颜色表 */
export const Color = {
    white: 'bg-white text-black',
    slate: 'bg-slate-400 text-white',
    gray: 'bg-gray-400 text-white',
    zinc: 'bg-zinc-400 text-white',
    neutral: 'bg-neutral-400 text-white',
    stone: 'bg-stone-400 text-white',
    red: 'bg-red-400 text-white',
    orange: 'bg-orange-400 text-white',
    amber: 'bg-amber-400 text-white',
    yellow: 'bg-yellow-400 text-white',
    lime: 'bg-lime-400 text-white',
    green: 'bg-green-400 text-white',
    emerald: 'bg-emerald-400 text-white',
    teal: 'bg-teal-400 text-white',
    cyan: 'bg-cyan-400 text-white',
    sky: 'bg-sky-400 text-white',
    blue: 'bg-blue-400 text-white',
    indigo: 'bg-indigo-400 text-white',
    violet: 'bg-violet-400 text-white',
    purple: 'bg-purple-400 text-white',
    fuchsia: 'bg-fuchsia-400 text-white',
    pink: 'bg-pink-400 text-white',
    rose: 'bg-rose-400 text-white',
};
/** 专属于 Button 的颜色表 */
export const OutlineColor = {
    white: 'bg-white text-black',
    slate: 'border-slate-400 text-slate-400',
    gray: 'border-gray-400 text-gray-400',
    zinc: 'border-zinc-400 text-zinc-400',
    neutral: 'border-neutral-400 text-neutral-400',
    stone: 'border-stone-400 text-stone-400',
    red: 'border-red-400 text-red-400',
    orange: 'border-orange-400 text-orange-400',
    amber: 'border-amber-400 text-amber-400',
    yellow: 'border-yellow-400 text-yellow-400',
    lime: 'border-lime-400 text-lime-400',
    green: 'border-green-400 text-green-400',
    emerald: 'border-emerald-400 text-emerald-400',
    teal: 'border-teal-400 text-teal-400',
    cyan: 'border-cyan-400 text-cyan-400',
    sky: 'border-sky-400 text-sky-400',
    blue: 'border-blue-400 text-blue-400',
    indigo: 'border-indigo-400 text-indigo-400',
    violet: 'border-violet-400 text-violet-400',
    purple: 'border-purple-400 text-purple-400',
    fuchsia: 'border-fuchsia-400 text-fuchsia-400',
    pink: 'border-pink-400 text-pink-400',
    rose: 'border-rose-400 text-rose-400',
};
export const SizeTrans = {
    mini: 'h-6 px-2 text-xs',
    small: 'h-8 px-3 text-sm',
    normal: 'h-10 px-4',
    large: 'h-12 px-4 text-lg',
};
